spring:
  cache:
    type: redis

  datasource:
    url: jdbc:mysql://localhost:3306/karan
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
  application:
    name: jwt-security


security:
  jwt:
    secret-key: R8v5NBy0FClM9mSZfHxAuo++jq/SOx82vKX1BMpbeTM=
    expiration-day: 86400000 # a day
    expiration-five-min: 300000